V2.1
solidusio-contrib/solidus_volume_pricing pull request #11
Opened 2017-04-24 11:00 UTC by seand7565

Updates this gem for Solidus 2.1 / Rails 5 compatibility.

All tests pass and everything seems to be in working order. The only necessary change was replacing "add_routes" - removed in Rails 5 - with "routes.draw" in config/routes.rb.

Unless I'm missing any obvious issues, this should solve #8

2017-04-24 11:25 UTC, seand7565 commented
But it worked on my machine!™

I'm not sure exactly what "NameError: uninitialized constant ActiveSupport::Deprecation::Reporting" means, but it seems to have something to do with building the dummy app. I'm able to reproduce it locally by removing my "dummy" folder and running the tests. Looking into it...

2017-04-24 12:22 UTC, mamhoff requested changes

2017-04-24 12:22 UTC, mamhoff commented on solidus_volume_pricing.gemspec
> +  s.add_runtime_dependency 'solidus_core', '~> 2.1'
If the only change necessary was using `routes.draw`, can this extension not depend on solidus `>= 1.3` instead? That way, you can also keep the build matrix for 1.3 and 1.4.

2017-04-24 12:38 UTC, seand7565 commented on solidus_volume_pricing.gemspec
> +  s.add_runtime_dependency 'solidus_core', '~> 2.1'
Yes, that makes sense. Additionally, changing the gemfile back to
branch = ENV.fetch('SOLIDUS_BRANCH', 'v1.3') 
fixes the strange Active Support error. I'll make the changes.

2017-04-24 18:06 UTC, seand7565 commented on solidus_volume_pricing.gemspec
> +  s.add_runtime_dependency 'solidus_core', '~> 2.1'
All tests now pass and it works with anything Solidus 1.3 and up. Anything else I need to do to get this up to snuff?

2017-04-24 18:48 UTC, tvdeyen submitted a review, later dismissed
Thanks. We should also test v2.0 in Travis. A git history rewrite would also be great but is not mandatory, we can also squash all the commits into one.

2017-04-24 18:48 UTC, tvdeyen commented on .travis.yml
> +    - SOLIDUS_BRANCH=v2.1 DB=mysql
2.0 is missing

2017-04-25 14:07 UTC, seand7565 commented on .travis.yml
> +    - SOLIDUS_BRANCH=v2.1 DB=mysql
Agreed and done - apologies on the mess here, I'm not super familiar with git or contributing in general yet. Thanks for bearing with me. 

Hopefully the last thing to solve is the strange testing error. I'll work on that and get something pushed either today or tomrrow.

2017-04-25 18:50 UTC, seand7565 commented
All passing at last! I needed to move the active_support/deprecation requirement before sass/rails - the gem that was calling for it. I am not a smart man. 😬

2017-04-27 18:26 UTC, seand7565 commented on .travis.yml
> +    - SOLIDUS_BRANCH=v2.1 DB=mysql
All done - anything else need doing to this? Thanks!

2017-04-28 09:31 UTC, mamhoff commented
@seand would you mind to squash those two commits again? Then this is ready to merge. Thank you, great work!

2017-04-28 13:25 UTC, seand7565 commented
Squashed as requested!

2017-04-28 15:10 UTC, mamhoff approved these changes

2017-04-28 15:15 UTC, merged